#!/bin/bash
RED='\033[0;31m'
GREEN='\033[0;32m'
CYAN='\033[0;36m'
YELLOW='\033[1;33m'
nc='\033[0m'

function update_with_network_reset {
        echo -e "${GREEN}\n--------------------------------------------${nc}"
        echo -e "${GREEN}Restarting the network service in 5 Seconds ${nc}"
        echo -e "${GREEN}----------------------------------------------${nc}\n"
        sleep 5;
        service network-manager restart
        echo -e "\nContinuing..."
        sleep 3;
        echo -e "${GREEN}\n-------------------------${nc}"
        echo -e "${GREEN}Updating all the REPOS's ${nc}"
        echo -e "${GREEN}-------------------------${nc}\n"

        cd /opt
        mr update

        echo -e "${GREEN}\n-------------------------${nc}"
        echo -e "${GREEN}Updating all the things ${nc}"
        echo -e "${GREEN}-------------------------${nc}\n"

        sudo apt update -y &&
        sudo apt full-upgrade -y &&
        sudo apt dist-upgrade -y &&
        sudo apt autoremove -y

        echo -e "${GREEN}\n-------------------------${nc}"
        echo -e "${GREEN}Updating GIT leakers ${nc}"
        echo -e "${GREEN}-------------------------${nc}\n"

        cd /opt/tools/gitleaks
        pip3 install -U gittyleaks
        cd /opt/tools/truffleHog
        pip3 install -U trufflehog

        echo -e "${GREEN}\n-------------------------${nc}"
        echo -e "${GREEN}Updating PIP ${nc}"
        echo -e "${GREEN}-------------------------${nc}\n"

        pip3 install --upgrade pip

        echo -e "${GREEN}\n-------------------------${nc}"
        echo -e "${CYAN}All done!! ${nc}"
        echo -e "${GREEN}-------------------------${nc}\n"
}

function update_no_network_reset {
        echo -e "${GREEN}\n--------------------------------------------${nc}"
        echo -e "${GREEN}NOT Restarting the network ${nc}"
        echo -e "${GREEN}----------------------------------------------${nc}\n"
        sleep 3;
        echo -e "\nContinuing..."
        sleep 3;
        echo -e "${GREEN}\n-------------------------${nc}"
        echo -e "${GREEN}Updating all the REPOS's ${nc}"
        echo -e "${GREEN}-------------------------${nc}\n"

        cd /opt
        mr update

        echo -e "${GREEN}\n-------------------------${nc}"
        echo -e "${GREEN}Updating all the things ${nc}"
        echo -e "${GREEN}-------------------------${nc}\n"

        sudo apt update -y &&
        sudo apt full-upgrade -y &&
        sudo apt dist-upgrade -y &&
        sudo apt autoremove -y

        echo -e "${GREEN}\n-------------------------${nc}"
        echo -e "${GREEN}Updating GIT leakers ${nc}"
        echo -e "${GREEN}-------------------------${nc}\n"

        cd /opt/tools/gitleaks
        pip3 install -U gittyleaks
        cd /opt/tools/truffleHog
        pip3 install -U trufflehog

        echo -e "${GREEN}\n-------------------------${nc}"
        echo -e "${GREEN}Updating PIP ${nc}"
        echo -e "${GREEN}-------------------------${nc}\n"

        pip3 install --upgrade pip

        echo -e "${GREEN}\n-------------------------${nc}"
        echo -e "${CYAN}All done!! ${nc}"
        echo -e "${GREEN}-------------------------${nc}\n"
}


echo -e "\nWould you like to restart the network? (y/n)"
read response

if [ $response == "y" ]; then
        update_with_network_reset
else
        update_no_network_reset
fi
